name: CI - Pruebas Hola Mundo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Dar permisos a jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Ejecutar pruebas
      run: npm test
